stage: stage_3_v2
benchmark: olympiad
n: 50
max_auto_reply: 10
max_judge_retries: 3

model:
  name: gpt-4.1
  base_url: https://llmproxy.uva.nl
  temperature: 0

judge_model:
  name: gemini-2.5-flash
  project: ingka-map-services-dev
  location: europe-west1
  temperature: 0

prompt: ../prompts/mathchat.txt
